name: Latest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    if: github.repository == 'JrMasterModelBuilder/homebrew-torrentcheck'

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Latest
        run: ./test/latest.sh

      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: ${{ env.KA_COMMIT_MESSAGE }}
          committer_username: ${{ env.KA_COMMIT_USER }}
          committer_email: ${{ secrets.KA_COMMIT_EMAIL }}
