name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        host:
          - runs-on: ubuntu-20.04
          - runs-on: macos-10.15
          - runs-on: macos-11
        package:
          - name: torrentcheck
            test: 0

    runs-on: ${{ matrix.host.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tap Dir
        run: mkdir -p "$(brew --repo)/Library/Taps/github"

      - name: Tap Link
        run: ln -s "$PWD" "$(brew --repo)/Library/Taps/github/homebrew-test"

      - name: Taps
        run: brew tap

      - name: Info
        run: brew info "github/test/${{ matrix.package.name }}"

      - name: Install
        run: brew install -v "github/test/${{ matrix.package.name }}"

      - name: Install
        run: brew audit --except=file,specs "github/test/${{ matrix.package.name }}"

      - name: Test
        run: brew test "github/test/${{ matrix.package.name }}"
        if: matrix.package.test == 1
