name: Ubuntu 22.04

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
          - host: ubuntu-22.04
            name: torrentcheck
            test: 0

    runs-on: ${{ matrix.config.host }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Tap Dir
        run: mkdir -p "$(dirname "$(brew --repo)/Library/Taps/${{ github.repository }}")"

      - name: Tap Link
        run: ln -s "$PWD" "$(brew --repo)/Library/Taps/${{ github.repository }}"

      - name: Info
        run: brew info "${{ matrix.config.name }}"

      - name: Install
        run: brew install -v "${{ matrix.config.name }}"

      - name: Installed
        run: brew info "${{ matrix.config.name }}"

      - name: Audit
        run: brew audit --except=file,specs "${{ matrix.config.name }}"

      - name: Test
        run: brew test "${{ matrix.config.name }}"
        if: matrix.config.test == 1
